---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: todos-api
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "apps/dev/todos-api/kustomization.yaml"
  prune: true
  timeout: 1m
