apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - includeSelectors: true
    pairs:
      variant: dev
resources:
  - ../../base

patches:
  - path: replica-count.yaml

configMapGenerator:
  - name: todos-configmap
    envs:
      - config.env
