---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - includeSelectors: true
    pairs:
      variant: dev
resources:
  - ../../base
  - middleware.yaml
  - ingressroute.yaml
  - namespace.yaml

patches:
  - path: replica-count.yaml

configMapGenerator:
  - name: todos-configmap
    envs:
      - config.env

patchesStrategicMerge:
  - deployment-patch.yaml

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: traefik
      namespace: traefik
    path: args-patch.yaml
