---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todos-api-deployment
spec:
  replicas: 1
  template:
    spec:
      imagePullSecrets:
        - name: playground-secret
      containers:
        - name: todos-api-container
          image: miketsap111/playground:todos-api-0.0.10 # {"$imagepolicy": "flux-system:playground-policy"}
          envFrom:
            - configMapRef:
                name: todos-configmap
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "100Mi"
            requests:
              memory: "100Mi"
              cpu: "50m"
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
