---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: todos

labels:
  - includeSelectors: true
    pairs:
      variant: dev
resources:
  - ./namespace.yaml
  - ../../base/todos-api/
  - ./ingressroute.yaml

patches:
  - path: replica-count.yaml

configMapGenerator:
  - name: todos-configmap
    envs:
      - config.env
