---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  template:
    spec:
      containers:
        - name: jellyfin
          image: lscr.io/linuxserver/jellyfin:10.10.7
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: Europe/Athens

          ports:
            - containerPort: 8096
          resources:
            requests:
              cpu: "0m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          volumeMounts:
            - name: config
              mountPath: /config
            - name: media
              mountPath: /media
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: jellyfin-config-pvc
        - name: media
          persistentVolumeClaim:
            claimName: jellyfin-media-pvc
      securityContext:
        seccompProfile:
          type: RuntimeDefault
