---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-media-pv
spec:
  storageClassName: "local-path"
  capacity:
    storage: 1000Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/mass/Videos
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-media-pvc
spec:
  storageClassName: "local-path"
  volumeName: jellyfin-media-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1000Gi
