---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: jellyfin-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: jellyfin
  filterTags:
    pattern: '^(?P<version>(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*))$'
    extract: '$version'
  policy:
    semver:
      range: ">=10.10.0"
