---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: jellyfin-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: jellyfin
  filterTags:
    pattern: '^(?P<version>\d+\.\d+\.\d+)$'
    extract: '$version'
  policy:
    semver:
      range: ">=10.10.0"
