---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: jellyfin-ingressroute
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`jellyfin.mtsap.io`)
      services:
        - kind: Service
          name: jellyfin
          namespace: jellyfin
          port: 8096
          scheme: http
