---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jellyfin

labels:
  - includeSelectors: true
    pairs:
      variant: dev
resources:
  - ./namespace.yaml
  - ../../base/jellyfin/
  - ./ingressroute.yaml
