---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  template:
    spec:
      runtimeClassName: nvidia
      containers:
        - name: jellyfin
          image: lscr.io/linuxserver/jellyfin:10.10.7
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: Europe/Athens
            - name: NVIDIA_VISIBLE_DEVICES
              value: "all"
            - name: NVIDIA_DRIVER_CAPABILITIES
              value: "compute,utility,video"
          ports:
            - containerPort: 8096
          resources:
            requests:
              cpu: "600m"
              memory: "2Gi"
            limits:
              cpu: "1000m"
              memory: "4Gi"
          volumeMounts:
            - name: config
              mountPath: /config
            - name: media
              mountPath: /media
            - name: dev-dri
              mountPath: /dev/dri
            - name: nvidia-devices
              mountPath: /dev/nvidia0
            - name: nvidia-uvm
              mountPath: /dev/nvidia-uvm
            - name: nvidia-uvm-tools
              mountPath: /dev/nvidia-uvm-tools
            - name: nvidiactl
              mountPath: /dev/nvidiactl
          securityContext:
            privileged: true
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: jellyfin-config-pvc
        - name: media
          persistentVolumeClaim:
            claimName: jellyfin-media-pvc
        - name: dev-dri
          hostPath:
            path: /dev/dri
        - name: nvidia-devices
          hostPath:
            path: /dev/nvidia0
        - name: nvidia-uvm
          hostPath:
            path: /dev/nvidia-uvm
        - name: nvidia-uvm-tools
          hostPath:
            path: /dev/nvidia-uvm-tools
        - name: nvidiactl
          hostPath:
            path: /dev/nvidiactl
      securityContext:
        seccompProfile:
          type: RuntimeDefault
