---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./config-storage.yaml
  - ./media-storage.yaml
  - ./deployment.yaml
  - ./service.yaml

namespace: jellyfin

labels:
  - includeSelectors: true
    pairs:
      app: jellyfin
