---
# helmreleases/loki.yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  chart:
    spec:
      chart: loki
      sourceRef:
        kind: HelmRepository
        name: grafana
      version: "2.8.1"
  interval: 5m
  values:
    persistence:
      enabled: true
      size: 5Gi
